### ISSUE TITLE
Restore the web

### ISSUE THREAD

**Issue by lzy37ld** [AScriver/MHTMLExtractor#4]
Hi!
I have used this repo and successfully parse many resources incluidng html and css etc..
However, when I open 127.0.0.1/web.html I just can not load the web normally?
I feel like it should action as the "Save As" feature by clicking on the right mouse and could normally restore the web?

**Comment by AScriver** [comment]
There is no web server being used in the project -- MHTMLExtractor.py only saves as files. You may be able to use http.server to get it serving from 127.0.0.1/localhost
